/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ala.entities;

import java.util.List;
import java.util.Objects;

/**
 *
 * @author Abimael
 */
public final class Request {
    private String id; //primary key autogenerated
    private String serviceId;
    
    private List<Material> requestForProgMaterials;

    public Request(String id, String serviceId, List<Material> requestForProgMaterials) {
        this.id = id;
        this.serviceId = serviceId;
        this.requestForProgMaterials = requestForProgMaterials;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getServiceId() {
        return serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public List<Material> getRequestForProgMaterials() {
        return requestForProgMaterials;
    }

    public void setRequestForProgMaterials(List<Material> requestForProgMaterials) {
        this.requestForProgMaterials = requestForProgMaterials;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Request other = (Request) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
       
}
