/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ala.gui;

import com.mycompany.ala.dao.DaoFactory;
import com.mycompany.ala.dao.MaterialDao;
import com.mycompany.ala.entities.Material;
import com.mycompany.ala.entities.RequestMaterial;
import com.mycompany.ala.entities.Service;
import com.mycompany.ala.entities.Structure;
import com.mycompany.ala.exceptions.DbException;
import com.mycompany.ala.models.BasicMaterialTableModel;
import com.mycompany.ala.models.StructureTableModel;
import com.mycompany.ala.models.RequestMaterialTableModel;
import com.mycompany.ala.models.StructureMaterialTableModel;
import com.mycompany.ala.models.StructureSummaryTableModel;
import com.mycompany.ala.services.DataChangeListener;
import com.mycompany.ala.util.DoubleConstraint;
import com.mycompany.ala.util.UpperCaseConstraint;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Abimael
 */
public class MaterialRequestView extends javax.swing.JFrame implements DataChangeListener {

    private Service service;
    private RequestMaterialTableModel requestMatModel = new RequestMaterialTableModel();
    private StructureSummaryTableModel structureSummaryModel = new StructureSummaryTableModel(requestMatModel);
    private BasicMaterialTableModel basicMatModel = new BasicMaterialTableModel();
    private StructureTableModel customMatModel = new StructureTableModel();
    private MaterialDao materialDao = DaoFactory.createMaterialDao();

    /**
     * Creates new form TestFrame
     */
    public MaterialRequestView(Service service, DataChangeListener parentView) {
        initComponents();
        configFields();
        configTables();
        requestMatModel.subscribeListener(parentView);
        if (service != null) {
            this.service = service;
            this.requestMatModel.setRequestMaterials(this.service.getRequest());
            this.structureSummaryModel.setRequestMaterials(this.service.getRequest());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBasicMaterials = new javax.swing.JTable();
        txtSearchMaterial = new javax.swing.JTextField();
        txtQuantMaterial = new javax.swing.JTextField();
        btnAddBasicMaterial = new javax.swing.JButton();
        btnAddStructure = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCustomMaterials = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConsultStructure = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRequestMaterials = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbStructureSummary = new javax.swing.JTable();
        btnRemoveStructure = new javax.swing.JButton();
        btnRemoveBasicMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        tbBasicMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBasicMaterials);

        btnAddBasicMaterial.setText("Inserir");
        btnAddBasicMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBasicMaterialActionPerformed(evt);
            }
        });

        btnAddStructure.setText("Inserir Estrutura");
        btnAddStructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStructureActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setText("Personalizados");

        jLabel2.setForeground(new java.awt.Color(100, 100, 100));
        jLabel2.setText("Quantidade");

        tbCustomMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbCustomMaterials);

        jLabel3.setForeground(new java.awt.Color(100, 100, 100));
        jLabel3.setText("Material");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 100, 100));
        jLabel4.setText("Básicos");

        btnConsultStructure.setText("Consultar");
        btnConsultStructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultStructureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchMaterial)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtQuantMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultStructure))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddStructure, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBasicMaterial)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBasicMaterial)
                    .addComponent(jLabel4)
                    .addComponent(btnAddStructure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultStructure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));

        tbRequestMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbRequestMaterials);

        tbStructureSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbStructureSummary);

        btnRemoveStructure.setText("Remover");
        btnRemoveStructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStructureActionPerformed(evt);
            }
        });

        btnRemoveBasicMaterial.setText("Remover");
        btnRemoveBasicMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBasicMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 543, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveStructure, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemoveBasicMaterial, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnRemoveBasicMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveStructure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBasicMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBasicMaterialActionPerformed
        if (this.service != null) {
            if (tbBasicMaterials.getSelectedRow() != -1) {
                Material material = basicMatModel.getMaterial(tbBasicMaterials.getSelectedRow());
                if (txtQuantMaterial.getText().trim().length() > 0 && Double.parseDouble(txtQuantMaterial.getText().trim()) != 0.0) {
                    RequestMaterial requestMaterial = new RequestMaterial(service.getId(), material.getCode(),
                            material.getDescription(), material.getUnits(),
                            Double.parseDouble(txtQuantMaterial.getText()), false);

                    try {
                        if (requestMatModel.getRequestMaterials().contains(requestMaterial)) {
                            for (RequestMaterial mat : requestMatModel.getRequestMaterials()) {
                                if (mat.equals(requestMaterial)) {
                                    requestMaterial.setRequestQuantity(mat.getRequestQuantity() + requestMaterial.getRequestQuantity());
                                }
                            }
                        }
                        if (materialDao.insertOrUpdateRequest(requestMaterial) > 0) {
                            requestMatModel.addMaterial(requestMaterial);
                        }
                    } catch (DbException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Digite uma quantidade válida.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um item.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Serviço não identificado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddBasicMaterialActionPerformed

    private void btnAddStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStructureActionPerformed
        if (this.service != null) {
            if (tbCustomMaterials.getSelectedRow() != -1) {
                Structure structure = customMatModel.getStructure(tbCustomMaterials.getSelectedRow());
                if (txtQuantMaterial.getText().trim().length() > 0 && Double.parseDouble(txtQuantMaterial.getText().trim()) != 0.0) {
                    RequestMaterial requestStructure = new RequestMaterial(service.getId(), structure.getCode().toString(),
                            structure.getDescription(), "CDA",
                            Double.parseDouble(txtQuantMaterial.getText()), true);
                    try {
                        if (structureSummaryModel.getStructuries().contains(requestStructure)) {
                            for (RequestMaterial mat : structureSummaryModel.getStructuries()) {
                                if (mat.getCode().equals(requestStructure.getCode())) {
                                    requestStructure.setRequestQuantity(mat.getRequestQuantity() + requestStructure.getRequestQuantity());
                                }
                            }
                        }
                        if (materialDao.insertOrUpdateRequest(requestStructure) > 0) {
                            structureSummaryModel.addStructure(requestStructure);
                        }
                    } catch (DbException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Digite uma quantidade válida.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um item.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Serviço não identificado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddStructureActionPerformed

    private void btnRemoveBasicMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBasicMaterialActionPerformed
        if (tbRequestMaterials.getSelectedRow() != -1) {
            RequestMaterial material = requestMatModel.getRequestBasicMaterial((tbRequestMaterials.getSelectedRow()));
            if (!material.isStructure()) {
                RemoveMaterialDialog dialogRemove = new RemoveMaterialDialog(this, true, material);
                dialogRemove.subscribeDataChangeListener(this);
                dialogRemove.setTitle("Remover material");
                dialogRemove.setLocationRelativeTo(null);
                dialogRemove.setResizable(false);
                dialogRemove.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Material de estruturas.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveBasicMaterialActionPerformed

    private void btnRemoveStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStructureActionPerformed
        if (tbStructureSummary.getSelectedRow() != -1) {
            RequestMaterial material = structureSummaryModel.getRequestStructure((tbStructureSummary.getSelectedRow()));
            RemoveMaterialDialog dialogRemove = new RemoveMaterialDialog(this, true, material);
            dialogRemove.subscribeDataChangeListener(this);
            dialogRemove.setTitle("Remover estrutura");
            dialogRemove.setLocationRelativeTo(null);
            dialogRemove.setResizable(false);
            dialogRemove.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveStructureActionPerformed

    private void btnConsultStructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultStructureActionPerformed
       Structure str = customMatModel.getStructure(tbCustomMaterials.getSelectedRow());
       JDialog structureMaterialDialog = new JDialog(this, true);
       structureMaterialDialog.setSize(500, 300);
       structureMaterialDialog.setLocationRelativeTo(null);
       JTable table = new JTable();
       table.setModel(new StructureMaterialTableModel(str.getMaterials()));
       structureMaterialDialog.add(table);
       structureMaterialDialog.setVisible(true);     
    }//GEN-LAST:event_btnConsultStructureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterialRequestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterialRequestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterialRequestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialRequestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaterialRequestView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBasicMaterial;
    private javax.swing.JButton btnAddStructure;
    private javax.swing.JButton btnConsultStructure;
    private javax.swing.JButton btnRemoveBasicMaterial;
    private javax.swing.JButton btnRemoveStructure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbBasicMaterials;
    private javax.swing.JTable tbCustomMaterials;
    private javax.swing.JTable tbRequestMaterials;
    private javax.swing.JTable tbStructureSummary;
    private javax.swing.JTextField txtQuantMaterial;
    private javax.swing.JTextField txtSearchMaterial;
    // End of variables declaration//GEN-END:variables

    private void configTables() {
        tbRequestMaterials.setModel(requestMatModel);
        tbRequestMaterials.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tbRequestMaterials.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                //----------------------------------------------------
                boolean structure = ((RequestMaterialTableModel) tbRequestMaterials.getModel()).getBasicRequestMaterials().get(row).isStructure();
                if (structure) {
                    label.setForeground(Color.red);
                } else {
                    label.setForeground(Color.black);
                }
                //----------------------------------------------------
                return label;
            }

        });

        tbStructureSummary.setModel(structureSummaryModel);
        tbStructureSummary.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbBasicMaterials.setModel(basicMatModel);
        tbBasicMaterials.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbCustomMaterials.setModel(customMatModel);
        tbCustomMaterials.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void configFields() {
        txtQuantMaterial.setDocument(new DoubleConstraint(6));
        txtSearchMaterial.setDocument(new UpperCaseConstraint(50));
        txtSearchMaterial.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                String content = txtSearchMaterial.getText().trim();
                basicMatModel.setFilter(m -> m.getDescription().contains(content) || m.getCode().contains(content));
            }
        });
    }

    private void fillTables(Service service) {
        List<RequestMaterial> basicMaterial = service.getRequest().stream().filter(m -> !m.isStructure()).collect(Collectors.toList());
        requestMatModel.setRequestMaterials(basicMaterial);
    }

    @Override
    public void onDataChange(Object obj) {
        try {
            if (obj != null) {
                RequestMaterial requestMaterial = (RequestMaterial) obj;
                if (!requestMaterial.isStructure()) {
                    if (materialDao.insertOrUpdateRequest(requestMaterial) > 0) {
                        requestMatModel.addMaterial(requestMaterial);
                    }
                } else {
                    if (materialDao.insertOrUpdateRequest(requestMaterial) > 0) {
                        structureSummaryModel.addStructure(requestMaterial);
                    }
                }
            }
        } catch (DbException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
}
