/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ala.gui;

import com.mycompany.ala.entities.OrderService;
import com.mycompany.ala.enums.OrderServiceFormType;
import com.mycompany.ala.models.OrderServiceTableModel;
import com.mycompany.ala.services.ImportSAPServicesData;
import com.mycompany.ala.services.ImportServicesFromFile;
import com.mycompany.ala.util.DefaultFileChooser;


import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.ListSelectionModel;

/**
 *
 * @author Abimael
 */
public class OrderServiceListView extends javax.swing.JFrame {

    private OrderServiceTableModel model = new OrderServiceTableModel(this);

    public OrderServiceListView() {
        initComponents();
        model.onDataChange(null);
        tbOrderServices.setModel(model);
        tbOrderServices.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrderServices = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnConsult = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnSap = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));

        tbOrderServices.setBackground(new java.awt.Color(220, 220, 220));
        tbOrderServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbOrderServices);

        jToolBar1.setBackground(new java.awt.Color(60, 60, 60));
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setOpaque(false);

        btnNew.setForeground(new java.awt.Color(150, 150, 150));
        btnNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\registerIcon.png")); // NOI18N
        btnNew.setBorder(null);
        btnNew.setBorderPainted(false);
        btnNew.setOpaque(false);
        btnNew.setRequestFocusEnabled(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnConsult.setForeground(new java.awt.Color(150, 150, 150));
        btnConsult.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\consult.png")); // NOI18N
        btnConsult.setToolTipText("");
        btnConsult.setBorderPainted(false);
        btnConsult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsult.setOpaque(false);
        btnConsult.setPreferredSize(new java.awt.Dimension(25, 25));
        btnConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsult);

        btnFilter.setForeground(new java.awt.Color(150, 150, 150));
        btnFilter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\filter.png")); // NOI18N
        btnFilter.setBorder(null);
        btnFilter.setBorderPainted(false);
        btnFilter.setOpaque(false);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilter);

        btnImport.setForeground(new java.awt.Color(150, 150, 150));
        btnImport.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\import.png")); // NOI18N
        btnImport.setBorderPainted(false);
        btnImport.setOpaque(false);
        btnImport.setPreferredSize(new java.awt.Dimension(25, 25));
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImport);

        btnSap.setForeground(new java.awt.Color(150, 150, 150));
        btnSap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\SAP.png")); // NOI18N
        btnSap.setBorderPainted(false);
        btnSap.setFocusable(false);
        btnSap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSap.setOpaque(false);
        btnSap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSap);

        btnExport.setForeground(new java.awt.Color(150, 150, 150));
        btnExport.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abimael\\Documents\\NetBeansProjects\\ala\\Resources\\icons\\export.png")); // NOI18N
        btnExport.setBorder(null);
        btnExport.setBorderPainted(false);
        btnExport.setFocusable(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnExport.setOpaque(false);
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar2.setBackground(new java.awt.Color(60, 60, 60));
        jMenuBar2.setForeground(new java.awt.Color(150, 150, 150));
        jMenuBar2.setBorderPainted(false);

        jMenu3.setForeground(new java.awt.Color(150, 150, 150));
        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(150, 150, 150));
        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        createOrderServiceFormView(null, OrderServiceFormType.NEW);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultActionPerformed
         
        if (tbOrderServices.getSelectedRow() != -1){
            OrderServiceFormView form = createOrderServiceFormView(this.model.getOrderService(tbOrderServices.getSelectedRow()), OrderServiceFormType.CONSULT_MODE);
            form.subscribeChangeListener(this.model);
        }
        else
            JOptionPane.showMessageDialog(this, "Selecione um serviço.");
    }//GEN-LAST:event_btnConsultActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importDataFromFile();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnSapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapActionPerformed
        JFileChooser fc = DefaultFileChooser.createFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getAbsolutePath();

            ImportSAPServicesData importSapServicesData = new ImportSAPServicesData(this, path);
            importSapServicesData.subscribeDataChangeListener(this.model);
            importSapServicesData.start();

        }
    }//GEN-LAST:event_btnSapActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed
    private void importDataFromFile() {
        JFileChooser fc = DefaultFileChooser.createFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getAbsolutePath();
            
            ImportServicesFromFile isff = new ImportServicesFromFile(this, path);
            isff.subscribeDataChangeListener(this.model);
            isff.start();
        }
    }

    private OrderServiceFormView createOrderServiceFormView(OrderService os, OrderServiceFormType type) {
        JDialog osfv = new JDialog(this, true);
        osfv.setResizable(false);
        OrderServiceFormView view = new OrderServiceFormView(os, type);
        view.subscribeChangeListener(this.model);
        osfv.setContentPane(view.getContentPane());

        osfv.setSize(view.getSize());
        osfv.setTitle("Ordem de Serviço");
        osfv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        osfv.setLocationRelativeTo(null);
        osfv.setVisible(true);
        
        return view;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderServiceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderServiceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderServiceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderServiceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderServiceListView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSap;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbOrderServices;
    // End of variables declaration//GEN-END:variables

}
