/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ala.gui;

import com.mycompany.ala.entities.OrderService;
import com.mycompany.ala.enums.OrderServiceFormType;
import com.mycompany.ala.models.ProgTableModel;
import com.mycompany.ala.models.RequestTableModel;
import com.mycompany.ala.models.ReservTableModel;
import com.mycompany.ala.util.DoubleConstraint;
import com.mycompany.ala.util.JSpinnerListener;
import com.mycompany.ala.util.MaxLengthConstraint;
import com.mycompany.ala.util.OnlyIntNumberConstraint;
import com.mycompany.ala.util.UpperCaseConstraint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

import javax.swing.SpinnerDateModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Abimael
 */
public class OrderServiceFormView extends javax.swing.JFrame {
    private static SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Map<String, String> invalidFields = new HashMap<>();
    private OrderService os;
    private OrderServiceFormType type = null;
    private ProgTableModel progTableModel = new ProgTableModel();
    private RequestTableModel requestTableModel = new RequestTableModel();
    private ReservTableModel reservTableModel = new ReservTableModel();

    /**
     * Creates new form OrderServiceFormView
     */
    public OrderServiceFormView(OrderService os, OrderServiceFormType type) {
        initComponents();
        configTables();
        configFields();
        this.os = os;
        this.type = type;
        setMode(type);
        fillFields(os);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRegisterDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblRegisterOwner = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtFiscal = new javax.swing.JTextField();
        btnLog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAlim = new javax.swing.JTextField();
        txtObjTec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        comboBoxType = new javax.swing.JComboBox<>();
        comboBoxExpenditure = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.DAY_OF_YEAR);
        spinnerCreateDate = new javax.swing.JSpinner(sm);
        cbCreateDate = new javax.swing.JCheckBox();
        SpinnerDateModel smConclusion = new SpinnerDateModel(date, null, null, Calendar.DAY_OF_YEAR);
        spinnerConclusion = new javax.swing.JSpinner(smConclusion);
        SpinnerDateModel smClose = new SpinnerDateModel(date, null, null, Calendar.DAY_OF_YEAR);
        spinnerClose = new javax.swing.JSpinner(smClose);
        txtReserv = new javax.swing.JTextField();
        btnAddReserv = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbReserv = new javax.swing.JTable();
        btnMaterialRequest = new javax.swing.JButton();
        btnNewProg = new javax.swing.JButton();
        btnProgEdit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbProg = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbMaterialRequest = new javax.swing.JTable();
        btnRemoveReserv = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescript = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setText("Id");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(100, 100, 100));
        jLabel4.setText("Lote");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(100, 100, 100));
        jLabel6.setText("Registrado em: ");

        lblRegisterDate.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisterDate.setForeground(new java.awt.Color(100, 100, 100));
        lblRegisterDate.setText("01/01/0001");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(100, 100, 100));
        jLabel10.setText("Projeto (R)");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setForeground(new java.awt.Color(100, 100, 100));
        jLabel18.setText("Criado em");

        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });

        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setForeground(new java.awt.Color(100, 100, 100));
        jLabel12.setText("Por:");

        lblRegisterOwner.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisterOwner.setForeground(new java.awt.Color(100, 100, 100));
        lblRegisterOwner.setText("User");

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setForeground(new java.awt.Color(100, 100, 100));
        jLabel21.setText("Fiscal");

        txtFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiscalActionPerformed(evt);
            }
        });

        btnLog.setText("Log");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(100, 100, 100));
        jLabel3.setText("Alimentador");

        txtAlim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlimActionPerformed(evt);
            }
        });

        txtObjTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObjTecActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(100, 100, 100));
        jLabel8.setText("Obj. Tec.");

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(100, 100, 100));
        jLabel9.setText("Local");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(100, 100, 100));
        jLabel5.setText("Km");

        txtKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmActionPerformed(evt);
            }
        });

        comboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "DEFEITO", "ENCAIXE", "ESTRUTURAL", "MELHORIA", "NDS", "PODA", "TERMOGRÁFICA", "RECLAMAÇÃO_DE_TENSÃO" }));
        comboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTypeActionPerformed(evt);
            }
        });

        comboBoxExpenditure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUSTEIO", "INVESTIMENTO" }));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setForeground(new java.awt.Color(100, 100, 100));
        jLabel15.setText("Tipo");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setForeground(new java.awt.Color(100, 100, 100));
        jLabel16.setText("Faturamento");

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGISTRADO", "CONTRATADO", "PROGRAMADO", "INICIADO", "CONCLUIDO", "ATUALIZADO", "PROTOCOLADO", "ENCERRADO", "EMBARGADO", "CANCELADO" }));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setForeground(new java.awt.Color(100, 100, 100));
        jLabel17.setText("Conclusão");

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setForeground(new java.awt.Color(100, 100, 100));
        jLabel22.setText("Status");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setForeground(new java.awt.Color(100, 100, 100));
        jLabel23.setText("Encerramento");

        btnEdit.setText("Editar");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(spinnerCreateDate, "dd/MM/yyyy");
        //de.getTextField().setFocusable(false);

        spinnerCreateDate.setEditor(de);
        spinnerCreateDate.setEnabled(false);

        cbCreateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreateDateActionPerformed(evt);
            }
        });

        //de.getTextField().setFocusable(false);
        JSpinner.DateEditor deConclusion = new JSpinner.DateEditor(spinnerConclusion, "dd/MM/yyyy");
        spinnerConclusion.setEditor(deConclusion);
        spinnerConclusion.setEnabled(false);

        //de.getTextField().setFocusable(false);
        JSpinner.DateEditor deClose = new JSpinner.DateEditor(spinnerClose, "dd/MM/yyyy");
        spinnerClose.setEditor(deClose);
        spinnerClose.setEnabled(false);

        txtReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservActionPerformed(evt);
            }
        });

        btnAddReserv.setText("Add");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(100, 100, 100));
        jLabel11.setText("Reserva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRegisterDate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRegisterOwner))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxType, 0, 170, Short.MAX_VALUE)
                                    .addComponent(comboBoxExpenditure, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLocal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtObjTec, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFiscal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel1))
                                                .addGap(7, 7, 7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLote, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(txtR)
                                            .addComponent(txtId)
                                            .addComponent(txtReserv))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddReserv))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinnerConclusion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(spinnerClose))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRegisterDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblRegisterOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddReserv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(spinnerCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtAlim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObjTec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(spinnerConclusion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(spinnerClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(220, 220, 220));

        tbReserv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbReserv);

        btnMaterialRequest.setText("Requisitar");

        btnNewProg.setText("Programar");

        btnProgEdit.setText("Editar");

        tbProg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbProg);

        tbMaterialRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbMaterialRequest);

        btnRemoveReserv.setText("Remover");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRemoveReserv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMaterialRequest))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnNewProg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProgEdit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewProg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoveReserv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaterialRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(220, 220, 220));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setForeground(new java.awt.Color(100, 100, 100));
        jLabel20.setText("Descrição");

        taDescript.setColumns(20);
        taDescript.setRows(5);
        jScrollPane2.setViewportView(taDescript);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    private void txtObjTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObjTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObjTecActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    private void txtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmActionPerformed

    private void txtFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiscalActionPerformed

    private void txtAlimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlimActionPerformed

    private void comboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTypeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (type != OrderServiceFormType.NEW) {
            setMode(OrderServiceFormType.EDIT_MODE);     
            fillFields(os);         
        } else {
            validateFields();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void cbCreateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCreateDateActionPerformed

    private void txtReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservActionPerformed

    public void setMode(OrderServiceFormType type) {
        switch (type) {
            case CONSULT_MODE:
                txtId.setEditable(false);
                enabledComponents(false);
                cbCreateDate.setEnabled(false);
                break;
            case EDIT_MODE:
                txtId.setEditable(false);
                enabledComponents(true);
                btnMaterialRequest.setEnabled(false);
                btnNewProg.setEnabled(false);
                btnProgEdit.setEnabled(false);
                btnEdit.setText("Confirmar");
                break;
            case NEW:
                btnEdit.setText("Confirmar");
                btnMaterialRequest.setEnabled(false);
                btnNewProg.setEnabled(false);
                btnProgEdit.setEnabled(false);
                btnLog.setEnabled(false);
                lblRegisterDate.setText("");
                break;
            case EMBARG_MODE:
                txtId.setEditable(false);
                enabledComponents(false);
                btnMaterialRequest.setEnabled(false);
                btnNewProg.setEnabled(false);
                btnProgEdit.setEnabled(false);
                break;
            default:
        }
    }

    private void enabledComponents(boolean enabled) {
        txtLote.setEditable(enabled);
        txtR.setEditable(enabled);
        txtReserv.setEnabled(enabled);
        btnAddReserv.setEnabled(enabled);
        btnRemoveReserv.setEnabled(enabled);
        txtFiscal.setEditable(enabled);
        txtAlim.setEditable(enabled);
        txtObjTec.setEditable(enabled);
        txtLocal.setEditable(enabled);
        txtKm.setEditable(enabled);
        comboBoxType.setEditable(enabled);
        comboBoxType.setEnabled(enabled);
        comboBoxExpenditure.setEnabled(enabled);
        comboBoxStatus.setEnabled(enabled);
        taDescript.setEditable(enabled);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderServiceFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderServiceFormView(null, OrderServiceFormType.NEW).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReserv;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMaterialRequest;
    private javax.swing.JButton btnNewProg;
    private javax.swing.JButton btnProgEdit;
    private javax.swing.JButton btnRemoveReserv;
    private javax.swing.JCheckBox cbCreateDate;
    private javax.swing.JComboBox<String> comboBoxExpenditure;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JComboBox<String> comboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblRegisterDate;
    private javax.swing.JLabel lblRegisterOwner;
    private javax.swing.JSpinner spinnerClose;
    private javax.swing.JSpinner spinnerConclusion;
    private javax.swing.JSpinner spinnerCreateDate;
    private javax.swing.JTextArea taDescript;
    private javax.swing.JTable tbMaterialRequest;
    private javax.swing.JTable tbProg;
    private javax.swing.JTable tbReserv;
    private javax.swing.JTextField txtAlim;
    private javax.swing.JTextField txtFiscal;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtObjTec;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtReserv;
    // End of variables declaration//GEN-END:variables

    private void fillFields(OrderService os) {
        if (os != null) {
            lblRegisterDate.setText(sdf.format(os.getRegisterDate()));
            txtId.setText(os.getId());
            
            if (os.getLote() != null && os.getLote().trim().length() > 0 && os.getLote().trim().matches("[+-]?\\d*(\\.\\d+)?"))                
                txtLote.setText(String.valueOf(Integer.parseInt(os.getLote().trim())));
            if (os.getR() != null && os.getR().trim().matches("[+-]?\\d*(\\.\\d+)?"))        
                txtR.setText(os.getR());
            if(os.getCreateDate() != null)
                spinnerCreateDate.setValue(os.getCreateDate());
            if(os.getFiscal() != null)
                txtFiscal.setText(os.getFiscal());
            if(os.getAlim() != null)
                txtAlim.setText(os.getAlim());
            if(os.getTechnicalObject() != null)
                txtObjTec.setText(os.getTechnicalObject());
            if(os.getLocal() != null)
                txtLocal.setText(os.getLocal());
            if(os.getUnlockKm() != null)
                txtKm.setText(String.valueOf(os.getUnlockKm()));
            if(os.getServiceType() != null)
                comboBoxType.setSelectedItem(String.valueOf(os.getServiceType()));     
            if(os.getExpenditureType() != null)
                comboBoxExpenditure.setSelectedItem(String.valueOf(os.getExpenditureType()));
//            comboBoxStatus.setSelectedItem("REGISTRADO");
//            
            if(os.getConclusionDate() != null)
                spinnerConclusion.setValue(os.getConclusionDate());
            if(os.getCloseDate() != null)
                spinnerClose.setValue(os.getCloseDate());
            if(os.getDescription() != null && os.getDescription().trim().length() > 0)
                taDescript.setText(os.getDescription());
        }
    }

    private boolean validateFields() {
        System.out.println("validatefields()");

        String id = txtId.getText();
        String Lote = txtLote.getText();
        String R = txtR.getText();
        String createDate = "";

        if (cbCreateDate.isSelected()) {
            createDate = spinnerCreateDate.getValue().toString();
        }

        String fiscal = txtFiscal.getText();
        String alim = txtAlim.getText();
        String objTec = txtObjTec.getText();
        String local = txtLocal.getText();
        String km = txtKm.getText();

        String type = comboBoxType.getSelectedItem().toString();
        String expenditureType = comboBoxExpenditure.getSelectedItem().toString();
        String status = comboBoxStatus.getSelectedItem().toString();

        return true;
    }

    private void configFields() {

        tbProg.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbMaterialRequest.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbReserv.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        txtId.setDocument(new MaxLengthConstraint(15));
        txtLote.setDocument(new OnlyIntNumberConstraint(7));
        txtR.setDocument(new OnlyIntNumberConstraint(6));
        txtReserv.setDocument(new OnlyIntNumberConstraint(9));
        txtFiscal.setDocument(new MaxLengthConstraint(40));
        txtAlim.setDocument(new MaxLengthConstraint(9));
        txtObjTec.setDocument(new UpperCaseConstraint(8));
        txtLocal.setDocument(new UpperCaseConstraint(8));
        txtKm.setDocument(new DoubleConstraint(8));

        //spinnerCreateDate
        JTextField txtCreateDate = ((JSpinner.DateEditor) spinnerCreateDate.getEditor()).getTextField();
        JSpinnerListener.setFixedLength(txtCreateDate, txtCreateDate.getText().length());
        JSpinnerListener.setDateChangeListener(spinnerCreateDate);

        //spinnerConclusion
        JTextField txtConclusion = ((JSpinner.DateEditor) spinnerConclusion.getEditor()).getTextField();
        JSpinnerListener.setFixedLength(txtConclusion, txtConclusion.getText().length());
        JSpinnerListener.setDateChangeListener(spinnerConclusion);

        //spinnerClose
        JTextField txtClose = ((JSpinner.DateEditor) spinnerClose.getEditor()).getTextField();
        JSpinnerListener.setFixedLength(txtClose, txtClose.getText().length());
        JSpinnerListener.setDateChangeListener(spinnerClose);

        cbCreateDate.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (cbCreateDate.isSelected()) {
                    spinnerCreateDate.setEnabled(true);
                } else {
                    spinnerCreateDate.setEnabled(false);
                }
            }
        });

        comboBoxStatus.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (comboBoxStatus.getSelectedItem().toString().equals("CONCLUIDO")) {
                    spinnerConclusion.setEnabled(true);
                    spinnerClose.setEnabled(false);
                } else if (comboBoxStatus.getSelectedItem().toString().equals("ENCERRADO")) {
                    spinnerClose.setEnabled(true);
                    spinnerConclusion.setEnabled(false);
                } else {
                    spinnerConclusion.setEnabled(false);
                    spinnerClose.setEnabled(false);
                }
            }
        });
    }

    private void configTables() {      
        tbProg.setModel(progTableModel);
        tbMaterialRequest.setModel(requestTableModel);
        tbReserv.setModel(reservTableModel);

    }
}
